name: CI

on:
  push:
    branches: [ main, clean ]
  pull_request:
    branches: [ main, clean ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10']

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Cache pip packages
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        python -c "import nltk; nltk.download('punkt', quiet=True); nltk.download('stopwords', quiet=True)"
    
    - name: Test with pytest
      run: |
        export PYTHONPATH="${PYTHONPATH}:$(pwd)"
        pytest tests/ -v --cov=src --cov-report=term-missing --tb=short 